### ISSUE TITLE
Request for issue details from OUJS

### ISSUE THREAD

**Issue by Martii** [skypesky/userjs#1]
What is the issue? *(what is the "news" ?)*

Re: https://openuserjs.org/scripts/motiko/Beautify_Salesforce_Debug_View/issues/Bad_%60require%60s#comment-1651d85291b

Btw the "Development" link at the bottom of every page takes you to OUJS dev where you can open an issue if you are having an issue or site suggestion *(after searching first of course)*.

If it's something inside a Userscript then we're probably not the right forum *(GH development)* for that unless it's a flag on a script... hence why I opened this issue here just in case.

OUJS Admin

**Comment by Martii** [comment]
I won't be able to add the fork history to the copied script until Wednesday evening however a few things:

Things that other user has done incorrectly:
1. Your copyright was stripped... TOS issue with lack of following `@license`.
2. Script is nearly the same using the Diff button compared to yours.


Things you have done incorrectly:
1. You should have used the "Flag" button on the script to keep this more confidential. That would have avoided the coy messages back and forth.
2. Once someone starts a discussion *(especially myself)* there's no need to mention my GH nick here as I'm already following it.

Things I can do when I get back to development station:
1. Add fork history but that doesn't address stripping of your copyright outside of OUJS.
2. Open an issue over there asking them to fix it.
3. If they don't respond they have violated the licensing and I can remove, at minimum, the script from their account.
4. Already flagged it for review from my moderation account.

So when I get back to town I will follow up with this. I would suggest that you "Flag" it as well. I'm not the only moderation person either and perhaps it will get addressed sooner.

**Comment by skypesky** [comment]
@Martii 
thank you for your help.
1. Regarding the problem of intercepting others, I was eager to seek your help before, and I am not sure that it will cause trouble for you. I am sorry for this.
2. If necessary, I will use the flag tag to submit questions, saving you time to solve problems.

**Comment by Martii** [comment]
Completed jobs:
1. Completed... marked as forked and moved the first few messages to the issue you created under your script instead of someone else.
2. See [here](https://openuserjs.org/scripts/kissaa6/[tbpublic]_%E6%B7%98%E5%AE%9D%E5%A4%A9%E7%8C%AB%E8%B4%AD%E7%89%A9%E4%BC%98%E6%83%A0%E5%88%B8_%E6%90%9C%E5%88%B8%E5%8A%A9%E6%89%8B_%E7%9C%81%E9%92%B1%E5%BF%85%E5%A4%87%E5%B7%A5%E5%85%B7%28%E7%9B%B4%E6%8E%A5%E6%98%BE%E7%A4%BA%E4%BC%98%E6%83%A0%E5%88%B8%29%282018-07-24%29/issues/Bad_forking).
3. This will be followed up when I get back next week.

Closing this as my Flag is in place along with a courtesy issue on OUJS. I will be back early next week to follow up with this. If there is no response I will deal with this accordingly.

> If necessary, I will use the flag tag to submit questions, saving you time to solve problems.

Since it's a Copyright issue yes it is necessary and confidential. We all see it at Admin and above. Keep it brief but at the same time clear so we can investigate it.

**Comment by skypesky** [comment]
@Martii 
If the other party replies to you, will we be able to do nothing? He can do whatever he wants with the code, and will not be punished, can not delete his code?

**Comment by Martii** [comment]
The script is removed for lack of response in a timely manner. If you notice the person doing it again please flag the script and we'll take some more action.
